"""
text_classifier.py
--------------------
A TF-IDF + Logistic Regression model that reads a free-text
description of a security incident (the kind an analyst would type
into an incident ticket) and predicts which threat category it
belongs to: malware, phishing, ransomware, ddos, sql_injection,
insider_threat, or network_intrusion.

Training data: a hand-written "curated" set of realistic analyst
descriptions (CURATED_SAMPLES) PLUS a much larger templated/synthetic
set (generated by generate_synthetic_samples() from per-category
sentence templates and vocabulary lists - the same well-established
data augmentation idea used to grow small NLP datasets). Combined,
the corpus has 1,000+ labeled examples, which is exported as a real
CSV dataset file (see export_dataset_csv()) for transparency/grading
alongside the trained model.

Evaluation uses stratified k-fold cross-validation (more reliable than
a single train/test split), and the deployed model is then re-fit on
the full corpus so every labeled example contributes to its
predictions. Note: even with 1,000+ examples, this is still template
generated text, and free-text incident classification realistically
tops out below 100% - a model claiming 100% on real-world phrasing
would almost always mean overfitting or a leaking/duplicated dataset,
not a genuinely better model. The number reported here is the true,
honestly measured cross-validation score.
"""

import os
import random
import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import FeatureUnion

import config

MODEL_PATH = os.path.join(config.AI_MODELS_DIR, "text_model.pkl")

CURATED_SAMPLES = {
    "phishing": [
        "User received an email pretending to be from the bank asking to verify account credentials",
        "Employee clicked a link in an email and entered their password on a fake login page",
        "Suspicious email impersonating IT support requesting password reset via external link",
        "An email with a spoofed sender address asked the finance team to update payment details",
        "Staff member reported a message claiming to be from HR asking to confirm login details",
        "A fake invoice email contained a link to a credential harvesting page",
        "Multiple employees received emails impersonating the CEO requesting urgent wire transfer",
        "User reported a text message claiming their package delivery requires payment confirmation",
        "A look alike domain was used to mimic the company webmail login portal",
        "Email attachment disguised as a shared document redirected to a fraudulent sign in page",
        "Voice call pretending to be tech support asked the user to share their one time password",
        "Spear phishing email targeted the accounting department with a fake vendor invoice",
        "Employees received text messages asking them to confirm a bank code on a suspicious link",
        "A cloned company login page was discovered hosted on a newly registered domain",
        "Social media message impersonated a recruiter and asked for personal identification documents",
        "An email claiming to be a delivery notice asked the recipient to pay a customs fee online",
        "A fraudulent message from a fake IT helpdesk requested the employee remote access code",
        "Phishing kit was discovered hosting a near identical copy of the company webmail page",
        "Attacker sent a calendar invite containing a malicious link disguised as a meeting room booking",
        "A scam email offered a fake prize and asked the user to log in to claim it",
        "Employees were lured into entering their credentials on a counterfeit single sign on page",
        "A text message impersonating the postal service asked for a small redelivery payment",
        "Fraudulent email requested gift card purchases on behalf of an impersonated executive",
        "A fake software update notification linked to a credential stealing website",
        "Attacker used a typo squatted domain to imitate the company's customer portal",
    ],
    "malware": [
        "Antivirus flagged an executable that attempts to modify system registry keys on startup",
        "A downloaded file was found to install a backdoor that communicates with a remote server",
        "Endpoint detection alerted on a process injecting code into another running application",
        "USB drive contained a trojan that copies itself to the startup folder",
        "An infected attachment dropped a malicious payload when opened",
        "System logs show unauthorized creation of a scheduled task running an unknown binary",
        "Workstation began making outbound connections to known command and control servers",
        "A keylogger was discovered running silently in the background of an employee laptop",
        "Antivirus quarantined a file disguised as a document that was actually an executable script",
        "Suspicious library file was side loaded by a legitimate application to evade detection",
        "A worm was found spreading across the internal network through shared folders",
        "Spyware was detected capturing screenshots and sending them to an external address",
        "A rootkit hid its presence by hooking low level operating system calls",
        "Fileless malware executed entirely in memory using scripting commands",
        "Adware bundled with a free software installer began displaying unwanted pop ups",
        "Security software detected a process attempting to disable the host firewall",
        "A malicious browser extension was found silently collecting saved passwords",
        "An infected machine began scanning the local network for other vulnerable hosts",
        "Sandboxing revealed the sample decrypts a hidden payload only when internet access is detected",
        "A trojanized installer was distributed through a compromised software download page",
        "Memory analysis revealed a process hollowing technique used to hide malicious code",
        "Persistence mechanism was found adding the malware to the system startup folder",
        "Command and control beacon traffic was detected at regular short intervals",
        "An unknown process was observed disabling endpoint logging shortly after execution",
        "Malicious macro inside a document downloaded and executed a second stage payload",
    ],
    "ransomware": [
        "All files on the shared drive were encrypted and a note demanded payment in cryptocurrency",
        "Employees discovered their documents renamed with an unfamiliar extension and a ransom note",
        "Backup server was also encrypted before the ransom message appeared on screens",
        "A pop up demanded payment within forty eight hours or the encryption key would be deleted",
        "File shares became inaccessible after a sudden spike in disk encryption activity",
        "The attacker threatened to leak stolen data unless the ransom was paid",
        "Hospital systems were locked out of patient records by an encryption based attack",
        "Network shares displayed a text file demanding cryptocurrency payment for file recovery",
        "Double extortion attack encrypted files and exfiltrated data before demanding payment",
        "Critical servers went offline simultaneously with a ransom demand displayed on screen",
        "Recovery attempts failed because backups had also been encrypted by the attacker",
        "A ransomware strain disabled the antivirus before beginning mass file encryption",
        "Employees were locked out of their workstations by a full disk encryption screen",
        "Attackers demanded a six figure payment after encrypting the entire finance department",
        "A ransom note appeared as the desktop wallpaper on every infected workstation",
        "Encrypted file extensions appeared across the network within a span of minutes",
        "The attacker provided a countdown timer threatening to double the ransom demand",
        "Shadow copies were deleted by the attacker before the encryption routine began",
        "A ransomware affiliate group claimed responsibility and published a leak site listing",
        "IT staff found every database file renamed with a random extension and a payment demand",
    ],
    "ddos": [
        "Web server became unreachable after receiving an unusually high volume of traffic",
        "Network monitoring detected a flood of connection requests overwhelming the firewall",
        "Customer facing application experienced downtime due to a distributed denial of service attack",
        "Traffic from thousands of distinct addresses targeted the login endpoint simultaneously",
        "Bandwidth usage spiked tenfold within minutes causing the website to time out",
        "A botnet was used to send amplified requests toward the company public facing server",
        "Application layer flood targeted the checkout page during a peak sales period",
        "Flood traffic saturated the company internet connection for several hours",
        "Load balancers failed after being overwhelmed with a massive number of requests",
        "Service became unavailable after a volumetric attack exceeded normal traffic by a huge margin",
        "Attackers used a reflection technique to amplify traffic directed at the target server",
        "The website slowed to a crawl after being targeted by a coordinated traffic flood",
        "Multiple data centers reported abnormal spikes in inbound connection attempts at the same time",
        "Mitigation service absorbed a large scale attack aimed at the company's primary domain",
        "Server resources were exhausted after thousands of simultaneous fake session requests",
        "Network engineers observed a sustained flood of traffic from a rented botnet infrastructure",
    ],
    "sql_injection": [
        "Web application logs show crafted input attempting to bypass login using database query syntax",
        "An attacker injected a union based statement into the search field to dump database records",
        "Penetration test revealed the customer portal was vulnerable to injection on the login form",
        "Database error messages were returned to the user after submitting malicious query characters",
        "Attacker used a quote and comment sequence to bypass the authentication check",
        "Automated scanner detected an endpoint vulnerable to a blind database injection technique",
        "Sensitive customer records were exposed after a successful injection attack on the order form",
        "Input validation was missing on the search bar allowing arbitrary database commands to run",
        "Attacker extracted the administrator password hash using a time based injection technique",
        "A crafted query parameter caused the application to reveal internal database table names",
        "Logs show repeated attempts to manipulate the query string with database control characters",
        "The vulnerability allowed an attacker to bypass authentication by altering the login query",
        "An unsanitized form field allowed an attacker to read arbitrary rows from the customer table",
        "Security testing confirmed the reporting tool was susceptible to a query manipulation attack",
        "Error based injection technique was used to enumerate the structure of the production database",
    ],
    "insider_threat": [
        "A departing employee copied confidential client data to a personal drive before resigning",
        "An employee accessed payroll records far outside their normal job responsibilities",
        "Audit logs show a staff member downloaded source code repositories shortly before quitting",
        "A privileged account was used outside business hours to access financial reports without approval",
        "An employee was found emailing proprietary design documents to a personal account",
        "Access logs reveal a contractor viewed customer records unrelated to their assigned project",
        "A system administrator disabled audit logging before making unauthorized configuration changes",
        "An employee shared their login credentials with a former colleague after leaving the company",
        "Unusual after hours access to the human resources database was traced to a disgruntled employee",
        "Sensitive intellectual property was uploaded to a personal cloud storage account by an employee",
        "A staff member was caught exporting the entire customer list shortly after a negative review",
        "Investigators found an employee had been quietly selling internal reports to a competitor",
        "An employee abused administrative access to read the private messages of coworkers",
        "A former employee's account was used to access internal systems weeks after their last day",
        "Data loss prevention tools flagged a large unauthorized transfer of files to removable media",
    ],
    "network_intrusion": [
        "Intrusion detection system flagged repeated failed login attempts from an external address",
        "Unauthorized lateral movement was detected between internal network segments",
        "An attacker exploited an unpatched remote access appliance to gain entry to the internal network",
        "Port scanning activity was detected probing the company's externally facing servers",
        "A misconfigured firewall rule allowed external access to an internal database server",
        "Logs show a successful brute force attack against the remote desktop service",
        "Network traffic analysis revealed data being exfiltrated to an unfamiliar external host",
        "An attacker gained a foothold by exploiting a known vulnerability in the file server",
        "Suspicious lateral movement used stolen credentials to access multiple internal systems",
        "Firewall logs show repeated connection attempts to an internal server from a foreign network range",
        "An attacker pivoted from a compromised workstation to reach the internal domain controller",
        "Unusual administrative logins were traced to a previously unseen external network range",
        "A compromised edge router was used as an entry point into the internal network",
        "Security monitoring detected reconnaissance scanning across the entire internal subnet",
        "An attacker used a stolen certificate to establish a trusted connection into the network",
    ],
}


# ---------------------------------------------------------------------------
# Templated / synthetic sample generation
# ---------------------------------------------------------------------------
# Each category gets several sentence "frames" with {placeholder} slots and
# vocabulary lists to fill them. Randomly combining frame x vocabulary choices
# produces a large number of realistic, grammatically valid, non-duplicate
# incident descriptions - the same data augmentation principle used to grow
# small labeled NLP datasets. This is what takes the corpus from ~130
# hand-written examples past 1,000 total labeled examples.
GENERATOR_CONFIG = {
    "phishing": {
        "templates": [
            "{target} received {medium} impersonating {brand} that asked them to {action}.",
            "{medium} pretending to be from {brand} pressured {target} to {action}.",
            "Staff reported {medium} requesting they {action}, claiming to be sent by {brand}.",
            "A spoofed message imitating {brand} convinced {target} to {action}.",
            "Investigators traced {medium} that tricked {target} into attempting to {action}.",
            "A look alike domain mimicking {brand} was used to get {target} to {action}.",
            "{target} were lured by {medium} disguised as {brand} into trying to {action}.",
            "Security flagged {medium} sent to {target} that impersonated {brand} and asked them to {action}.",
            "A fraudulent message claiming to be {brand} asked {target} to {action}.",
            "{medium} spoofing {brand} was used in an attempt to get {target} to {action}.",
            "Why did {medium} claiming to be {brand} ask {target} to {action}?",
            "Ticket: {target} got {medium} pretending to be {brand} and almost agreed to {action}.",
            "Can you check why {medium} impersonating {brand} wants {target} to {action}?",
            "Flagged: {target} received {medium} from someone posing as {brand}, pushing them to {action}.",
            "Heads up, {medium} pretending to be {brand} is going around asking {target} to {action}.",
        ],
        "vocab": {
            "brand": ["the bank", "PayPal", "Microsoft 365", "the IT helpdesk", "Amazon",
                       "the HR department", "a delivery courier", "the company CEO",
                       "a software vendor", "the payroll provider", "Google Workspace",
                       "the company's bank", "a cloud storage provider",
                       "the benefits administrator", "a major airline"],
            "medium": ["an email", "a text message", "a phone call", "a social media message",
                        "a voicemail", "a calendar invite", "a chat message", "a fake invoice",
                        "an SMS alert"],
            "action": ["verify their account credentials", "reset their password through an external link",
                        "confirm a recent wire transfer", "enter their login details on a linked page",
                        "share a one time passcode", "click a link to claim a refund",
                        "update their billing information", "download an urgent attachment",
                        "approve a pending payment request", "log in through a cloned portal",
                        "provide their employee ID and password", "scan a QR code to verify their identity"],
            "target": ["the finance team", "a new employee", "the accounting department",
                        "several staff members", "an executive assistant", "the customer support team",
                        "a remote employee", "the procurement team"],
        },
    },
    "malware": {
        "templates": [
            "{detector} flagged {artifact} that attempts to {behavior}.",
            "{artifact} was found to {behavior} after being executed on a workstation.",
            "{detector} discovered {artifact} silently trying to {behavior}.",
            "Investigation revealed {artifact} designed to {behavior}.",
            "A compromised host showed signs of {artifact} that began to {behavior}.",
            "Analysis confirmed {artifact} was responsible for an attempt to {behavior}.",
            "{detector} observed unusual activity traced back to {artifact} attempting to {behavior}.",
            "Forensic review found {artifact} on the system configured to {behavior}.",
            "{artifact} bundled with a legitimate download was found to {behavior}.",
            "A quarantined sample identified as {artifact} was confirmed to {behavior}.",
            "Why does {artifact} keep trying to {behavior}?",
            "Ticket: found {artifact} on a machine that seems to {behavior}.",
            "Can someone check {artifact} that appears to {behavior}?",
            "{detector} caught {artifact} trying to {behavior}, any idea why?",
            "Noticed {artifact} quietly attempting to {behavior} this morning.",
        ],
        "vocab": {
            "artifact": ["an executable", "a downloaded file", "a browser extension", "a USB drive",
                          "an email attachment", "a software installer", "a scheduled task",
                          "a system process", "a shared library file", "a portable application",
                          "a macro enabled document", "a firmware update file"],
            "behavior": ["modify system registry keys on startup", "install a backdoor that contacts a remote server",
                          "inject code into another running process", "disable the host firewall",
                          "capture keystrokes and send them externally", "hide its presence using rootkit techniques",
                          "spread across shared network folders", "encrypt portions of memory to evade detection",
                          "download a second stage payload", "beacon to a command and control server at regular intervals",
                          "disable endpoint logging shortly after execution", "create a hidden scheduled task for persistence"],
            "detector": ["Antivirus software", "Endpoint detection tooling", "A security analyst",
                          "Network monitoring", "Sandboxing analysis", "Threat hunting", "The SOC team",
                          "Behavioral analysis"],
        },
    },
    "ransomware": {
        "templates": [
            "Files on {target_system} were encrypted and the attacker demanded {demand}.",
            "{target_system} became inaccessible after a ransomware attack demanding {demand}.",
            "A ransom note appeared after {target_system} was encrypted, demanding {demand}.",
            "{extra}, and {target_system} was hit by an encryption based attack demanding {demand}.",
            "An extortion attempt encrypted {target_system} while demanding {demand}.",
            "Investigators found {target_system} locked by ransomware, with attackers demanding {demand}.",
            "{extra}, while {target_system} remained encrypted and attackers demanded {demand}.",
            "A ransomware strain spread to {target_system}, with the note demanding {demand}.",
            "Why are files on {target_system} suddenly locked, with a message demanding {demand}?",
            "Ticket: {target_system} got hit and now there is a note demanding {demand}.",
            "Can someone explain why {target_system} is encrypted and the attacker wants {demand}?",
            "{extra}, and now {target_system} is locked with a demand for {demand}.",
        ],
        "vocab": {
            "target_system": ["the shared drive", "the finance department's files", "patient record systems",
                                "backup servers", "the entire file server", "production databases",
                                "employee workstations", "the document management system",
                                "network attached storage", "the email archive server"],
            "demand": ["payment in cryptocurrency", "a six figure ransom within forty eight hours",
                        "an untraceable payment to unlock the files",
                        "a ransom paid in bitcoin before a countdown expired",
                        "a large payment or the stolen data would be leaked",
                        "payment via an anonymous portal listed in the ransom note"],
            "extra": ["Shadow copies had also been deleted beforehand", "Backups were found encrypted as well",
                        "The attacker threatened to publish stolen data",
                        "Security software had been disabled just before the attack",
                        "A leak site later listed the company as a victim",
                        "Recovery without the decryption key proved impossible"],
        },
    },
    "ddos": {
        "templates": [
            "{asset} {effect} after being hit with {attack_desc}.",
            "Network monitoring detected {attack_desc} aimed at {asset}, which {effect}.",
            "{asset} {effect} when {attack_desc} overwhelmed available capacity.",
            "A distributed denial of service attack used {attack_desc} against {asset}, which {effect}.",
            "Engineers reported {asset} {effect} during {attack_desc}.",
            "{attack_desc} targeted {asset}, causing it to {effect}.",
            "Why is {asset} down again, is it {attack_desc}?",
            "Ticket: {asset} {effect} and the logs point to {attack_desc}.",
            "Can you check if {attack_desc} is why {asset} {effect}?",
            "Seeing {attack_desc} hitting {asset}, which {effect}.",
        ],
        "vocab": {
            "asset": ["the public website", "the customer login endpoint", "the checkout page",
                        "the company's primary domain", "the API gateway", "the VPN concentrator",
                        "the load balancer", "the DNS infrastructure", "the customer support portal",
                        "the company's main data center"],
            "attack_desc": ["an unusually high volume of traffic",
                              "a flood of connection requests from thousands of distinct addresses",
                              "a volumetric attack exceeding normal traffic by a huge margin",
                              "a coordinated botnet driven traffic surge", "an amplified reflection attack",
                              "a sustained flood lasting several hours", "a sudden tenfold spike in bandwidth usage",
                              "an application layer flood during a peak traffic period"],
            "effect": ["became unreachable", "experienced significant downtime", "slowed to a crawl for several hours",
                        "timed out for most users", "required a mitigation service to absorb the attack",
                        "was taken offline for emergency maintenance"],
        },
    },
    "sql_injection": {
        "templates": [
            "An attacker used {technique} against {surface} to {outcome}.",
            "{surface} was found vulnerable to {technique}, allowing an attacker to {outcome}.",
            "Logs show {technique} submitted through {surface} in an attempt to {outcome}.",
            "A penetration test revealed {surface} could be exploited with {technique} to {outcome}.",
            "Security testing confirmed {technique} on {surface} could be used to {outcome}.",
            "An automated scanner detected {technique} on {surface}, which could {outcome}.",
            "Input validation was missing on {surface}, letting {technique} {outcome}.",
            "Why did {surface} return strange results after someone tried {technique}?",
            "Ticket: looks like {technique} on {surface} might {outcome}.",
            "Can someone check if {surface} is exposed to {technique} that could {outcome}?",
            "Found {technique} attempts on {surface} aiming to {outcome}.",
        ],
        "vocab": {
            "surface": ["the login form", "the search field", "the customer portal", "the order form",
                          "a reporting tool", "the password reset page", "an API query parameter",
                          "the account lookup page", "the support ticket form", "a public facing search endpoint"],
            "technique": ["a union based statement", "a blind injection technique", "a time based injection technique",
                            "an error based injection technique", "a crafted quote and comment sequence",
                            "malicious query characters", "an unsanitized input string", "a manipulated query parameter"],
            "outcome": ["dump database records", "bypass the login authentication check",
                          "reveal internal database table names", "extract the administrator password hash",
                          "expose sensitive customer records", "enumerate the structure of the production database",
                          "read arbitrary rows from a protected table",
                          "return raw database error messages to the attacker"],
        },
    },
    "insider_threat": {
        "templates": [
            "{detection_src} revealed that {actor} {action2}.",
            "{actor} was found to have {action2}, according to {detection_src}.",
            "{detection_src} flagged {actor} after they {action2}.",
            "An investigation confirmed {actor} had {action2}.",
            "{detection_src} traced unusual activity to {actor}, who had {action2}.",
            "It was discovered that {actor} {action2} without authorization.",
            "Why did {actor} {action2}, is that normal?",
            "Ticket: {detection_src} shows {actor} {action2}.",
            "Can someone explain why {actor} {action2}?",
            "Flagged: {actor} {action2}, according to {detection_src}.",
        ],
        "vocab": {
            "actor": ["a departing employee", "a disgruntled staff member", "a contractor",
                        "a system administrator", "a former employee", "an employee under financial pressure",
                        "a privileged account holder", "a recently demoted manager"],
            "action2": ["copied confidential client data to a personal drive",
                          "accessed payroll records outside their normal duties",
                          "downloaded source code repositories shortly before resigning",
                          "exported the entire customer list after a negative review",
                          "emailed proprietary design documents to a personal account",
                          "disabled audit logging before making unauthorized changes",
                          "shared login credentials with someone outside the company",
                          "uploaded sensitive files to a personal cloud storage account",
                          "viewed records unrelated to their assigned project",
                          "accessed systems weeks after their last working day"],
            "detection_src": ["Audit logs", "Data loss prevention tooling", "Access reviews",
                                "An internal investigation", "Security monitoring", "A routine compliance audit"],
        },
    },
    "network_intrusion": {
        "templates": [
            "An attacker exploited {vector} to gain a foothold, followed by {movement}.",
            "{detect_src2} flagged {movement} after {vector} was exploited.",
            "{vector} allowed an attacker to enter the network, leading to {movement}.",
            "{detect_src2} detected {movement} that was traced back to {vector}.",
            "Investigators found that {vector} enabled the attacker to carry out {movement}.",
            "An intrusion began with {vector} and progressed to {movement}.",
            "Why is there {movement} coming from {vector}?",
            "Ticket: {detect_src2} shows {movement} after {vector}.",
            "Can you check why {vector} led to {movement}?",
            "Seeing {movement}, looks like it started with {vector}.",
        ],
        "vocab": {
            "vector": ["an unpatched remote access appliance", "a misconfigured firewall rule",
                        "a brute force attack against remote desktop", "a known vulnerability in the file server",
                        "stolen credentials", "a compromised edge router", "a phishing foothold on a workstation",
                        "an exposed administrative interface"],
            "movement": ["lateral movement between internal network segments",
                          "a pivot to the internal domain controller",
                          "reconnaissance scanning across the internal subnet",
                          "data exfiltration to an unfamiliar external host",
                          "repeated connection attempts from a foreign network range",
                          "unauthorized administrative logins from an unfamiliar location",
                          "access to multiple internal systems using stolen credentials"],
            "detect_src2": ["Intrusion detection systems", "Firewall logs", "Network traffic analysis",
                              "Security monitoring", "An internal audit", "The SOC team"],
        },
    },
}


# ---------------------------------------------------------------------------
# Held-out evaluation set
# ---------------------------------------------------------------------------
# These sentences are written in a deliberately DIFFERENT register than both
# CURATED_SAMPLES (formal third-person analyst notes) and the templates above
# (consistent frame + vocabulary slots): short tickets, first-person reports,
# questions, casual phrasing. They are NEVER used for training - only to
# measure how well the model generalizes to phrasing it has not seen, which
# is a far more honest accuracy signal than cross-validating on the training
# distribution alone (where near-duplicate templated sentences can land in
# both the train and validation fold and inflate the score).
HOLDOUT_SAMPLES = {
    "phishing": [
        "Why did IT ask me to reset my password through a link in a text instead of the usual portal?",
        "Ticket: user clicked a link from what looked like our travel booking site and now his email account is sending spam.",
        "Caller ID showed our bank's number but the rep asked for my full card number and PIN over the phone.",
        "Someone signed into the CFO's calendar and sent a meeting invite with a fake video call link to the whole leadership team.",
        "I got a message from a recruiter who wanted my passport scan before a first interview.",
        "The IT survey email had our logo perfectly copied but linked to an unfamiliar domain instead of our usual site.",
        "A vendor invoice came in with our supplier's name spelled correctly but the bank account number had changed without notice.",
        "A QR code on a flyer in the break room led to a page asking staff to sign in with their work email and password.",
        "Front desk got a call from someone claiming to be from corporate security needing the visitor log emailed immediately.",
        "User said the license expired pop up wanted a credit card number to renew.",
    ],
    "malware": [
        "Laptop started running painfully slow right after opening a cracked design tool downloaded off a forum.",
        "Why does the task manager show an unfamiliar process using eighty percent of the CPU at two in the morning every night?",
        "Found a script in the startup folder that nobody on the team remembers adding.",
        "A printer driver installer from a mirror site also dropped a hidden file nobody asked for.",
        "Several machines on the same floor started flashing the same warning pop up within minutes of each other.",
        "The resume attachment triggered our sandbox to flag outbound traffic to an unfamiliar address.",
        "A game mod downloaded from a fan site quietly added a new browser toolbar and changed the default search engine.",
        "An old printer firmware update turned out to contain code that contacts an external server every hour.",
        "An employee's webcam light kept turning on by itself even when no video app was open.",
        "Security tooling caught a process trying to read saved browser passwords right after a free utility install.",
    ],
    "ransomware": [
        "Why can't anyone open the shared drive this morning, and why do all the file icons look different now?",
        "The server room monitor just shows a countdown timer and a wallet address on a black background.",
        "The backup job failed last night and now the backup target folder is also full of unreadable files.",
        "The front office got a printed note from the printer demanding payment, even though nobody sent a print job.",
        "The billing team can't pull up any invoices since this morning's unexpected system update.",
        "The attacker left a note claiming they already copied our HR files before locking everything.",
        "Every file on the design team's drive now opens as gibberish and there is a popup asking for payment.",
        "IT says recovery is not simple because even last week's backup snapshot was affected overnight.",
        "Factory floor controllers froze with a payment demand displayed on the touchscreen panels.",
        "Legal flagged a public listing of our company name with a countdown to publish stolen contracts.",
    ],
    "ddos": [
        "Why is the support chat widget timing out for everyone since this morning?",
        "Our hosting provider just reached out asking if we authorized fifty times our normal bandwidth usage overnight.",
        "Checkout keeps spinning during the sale and our error logs are full of connection resets.",
        "The dashboard shows requests coming from nearly every country at once, which never happens.",
        "The support page has been unreachable for three hours and even our status page will not load.",
        "Mobile app users are reporting login timeouts that started right after a routine announcement.",
        "Our content delivery provider says they are absorbing an attack aimed specifically at our login API.",
        "Office internet has been crawling and IT thinks it is not us, it is an attack on the shared upstream provider.",
        "Why did the uptime monitor send forty alerts in five minutes for the very same endpoint?",
        "Game servers kept disconnecting players in waves that match a pattern engineers called a pulse attack.",
    ],
    "sql_injection": [
        "Someone typed a single quote into the username field and the error page printed our database version.",
        "A researcher says they can read the entire orders table by tweaking the product identifier in the page address.",
        "Why did the search bar return every customer record when someone typed a quote followed by an always true condition?",
        "Our web firewall logs show repeated attempts with database keywords stuffed into the promo code field.",
        "The penetration test report flagged the newsletter signup form as letting attackers read arbitrary tables.",
        "Support noticed the order lookup page sometimes leaks raw database error text straight to the browser.",
        "Someone posted a working trick online that bypasses our login by neutralizing the password check entirely.",
        "A scan flagged the invoice number filter as vulnerable to a slow, guess based extraction technique.",
        "Why does adding a stray character to the coupon field crash checkout with a database stack trace?",
        "Our sorting parameter accepts raw column names, and a tester used it to pull password hashes from the admin table.",
    ],
    "insider_threat": [
        "Why did someone on the warehouse team download the entire customer database the day before they resigned?",
        "HR flagged that a manager kept full administrative access for three weeks after moving to a different department.",
        "Compliance noticed a contractor's badge was used to enter the server room overnight with no ticket on file.",
        "Someone forwarded next quarter's pricing sheet to a personal account right before joining a competitor.",
        "An employee's account pulled every staff member's salary record, even though their role has nothing to do with payroll.",
        "Why does the audit trail show the same administrator account active in two different cities within an hour?",
        "A soon to be former employee printed a stack of confidential client contracts the night before their last day.",
        "Someone quietly disabled their screen recording right before copying design files to a removable drive.",
        "Legal found out a departing partner had been quietly copying themselves on every deal email for months.",
        "IT noticed a service account that should only run backups was instead used to browse a different team's shared folder.",
    ],
    "network_intrusion": [
        "Why is there a login from a country we do not operate in on the administrative remote access account?",
        "Firewall logs show the same external address knocking on every port of our public server, one by one.",
        "Someone used the guest network to reach a printer that should only be visible internally.",
        "The domain controller logged an administrator login at three in the morning from a device that is supposed to be in storage.",
        "A contractor's old remote access credentials, which were never revoked, were used to connect last weekend.",
        "Why did the file server suddenly start communicating with a server in a country none of our offices are in?",
        "The network team noticed traffic moving from the guest network straight into the finance segment, which should not be possible.",
        "An old, unpatched appliance on the network map turned out to be the entry point for everything that followed.",
        "Someone is trying every common administrator password against our exposed remote access service.",
        "Two networks that were supposed to be separated turned out to be bridged, and that bridge reached payroll systems.",
    ],
}


# A second, separate held-out set written the way a typical user of the
# live Analyzer page actually types - fairly direct, often naming the
# attack type or its standard symptoms, the way a real analyst/student
# would describe an incident (as opposed to HOLDOUT_SAMPLES above, which
# deliberately uses indirect, symptom-only phrasing to stress-test the
# model's limits). Reported separately because it is the more relevant
# number for "how will this perform when someone actually uses it."
REALISTIC_TEST_SAMPLES = {
    "phishing": [
        "I got an email that looks like it's from our bank asking me to log in and verify my account.",
        "An employee clicked a phishing link and entered their work password on a fake Office 365 page.",
        "Someone is sending fake invoices that look like they are from our usual supplier.",
        "A text message claiming to be from the delivery company asked for a small fee to release my package.",
        "Our CEO's email was spoofed to request an urgent wire transfer from finance.",
        "A fake login page identical to our company portal was found hosted on a newly registered domain.",
        "A scam call pretending to be tech support asked for remote access to my computer.",
    ],
    "malware": [
        "Antivirus detected a trojan on one of our laptops that was trying to contact a remote server.",
        "A USB drive plugged into a workstation installed malware that spread to the shared folder.",
        "We found a keylogger running on an employee's computer.",
        "An infected email attachment installed a backdoor when it was opened.",
        "A process on the server is injecting code into other running applications.",
        "A downloaded cracked software installer turned out to contain a virus.",
        "Spyware was found capturing screenshots and sending them to an external IP address.",
    ],
    "ransomware": [
        "All our files got encrypted overnight and there is a ransom note asking for bitcoin payment.",
        "Our shared drive is locked by ransomware and a message is demanding payment to decrypt it.",
        "A ransomware attack encrypted our backup server as well as the main files.",
        "We received a ransom demand after our network was hit by an encryption attack.",
        "Employees can't access their files because ransomware encrypted the entire department's drive.",
        "An attacker threatened to leak our data unless we paid the ransomware demand.",
        "Our company was hit by ransomware and IT is trying to restore from backups.",
    ],
    "ddos": [
        "Our website went down because of a huge spike in traffic that looks like a DDoS attack.",
        "The login page keeps timing out due to an overwhelming flood of requests.",
        "We are experiencing a denial of service attack on our main server.",
        "Network traffic suddenly spiked to ten times normal and our site became unreachable.",
        "Our API is being flooded with requests from thousands of different IP addresses.",
        "A botnet appears to be flooding our servers with traffic, causing an outage.",
        "Our hosting provider says we are under a volumetric DDoS attack right now.",
    ],
    "sql_injection": [
        "An attacker used SQL injection to access our customer database through the login form.",
        "Our search bar is vulnerable to SQL injection and exposed database records.",
        "A penetration tester found a SQL injection vulnerability in the order form.",
        "Someone bypassed our login using a SQL injection attack on the password field.",
        "Our website's input fields are not sanitized, allowing SQL injection attacks.",
        "A hacker exploited a SQL injection flaw to dump our entire user table.",
        "A vulnerability scan flagged SQL injection risk in our reporting tool.",
    ],
    "insider_threat": [
        "An employee downloaded confidential files right before resigning from the company.",
        "A staff member accessed payroll data they had no business reason to view.",
        "We suspect an insider has been leaking internal documents to a competitor.",
        "A former employee's account was used to access company systems after they left.",
        "An employee was caught copying customer data to a personal USB drive.",
        "A contractor exported sensitive files they weren't authorized to access.",
        "An insider threat was detected when an employee emailed confidential reports to their personal account.",
    ],
    "network_intrusion": [
        "An attacker gained unauthorized access to our internal network through a vulnerable VPN.",
        "We detected lateral movement inside our network after a server was compromised.",
        "Someone breached our firewall and is moving between internal systems.",
        "An unauthorized login was detected on our domain controller from an external IP.",
        "Our network was infiltrated through an unpatched remote access device.",
        "We found evidence of a network intrusion with data being exfiltrated to an external host.",
        "An attacker used stolen credentials to break into our internal network.",
    ],
}


def _build_holdout():
    texts, labels = [], []
    for category, samples in HOLDOUT_SAMPLES.items():
        for s in samples:
            texts.append(s)
            labels.append(category)
    return texts, labels


def _build_realistic_test():
    texts, labels = [], []
    for category, samples in REALISTIC_TEST_SAMPLES.items():
        for s in samples:
            texts.append(s)
            labels.append(category)
    return texts, labels


def generate_synthetic_samples(per_category=150, seed=42):
    """Use the frame + vocabulary templates above to generate a large set
    of additional labeled examples per category. Returns (texts, labels).
    """
    rng = random.Random(seed)
    texts, labels = [], []

    for category, cfg in GENERATOR_CONFIG.items():
        templates = cfg["templates"]
        vocab = cfg["vocab"]
        seen = set()
        attempts = 0
        while len(seen) < per_category and attempts < per_category * 40:
            attempts += 1
            template = rng.choice(templates)
            slot_names = [s.split("}")[0] for s in template.split("{")[1:]]
            fill = {name: rng.choice(vocab[name]) for name in set(slot_names)}
            sentence = template.format(**fill)
            sentence = sentence[0].upper() + sentence[1:] if sentence else sentence
            if sentence not in seen:
                seen.add(sentence)
        for sentence in seen:
            texts.append(sentence)
            labels.append(category)

    return texts, labels


def export_dataset_csv(path=None, per_category=150, seed=42):
    """Write the full combined (curated + generated) labeled text dataset
    to a CSV file so it exists as a real, inspectable dataset artifact -
    exactly the rows the model is trained on.
    """
    import csv
    if path is None:
        path = os.path.join(config.AI_MODELS_DIR, "..", "datasets", "text_incidents_dataset.csv")
    path = os.path.abspath(path)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    texts, labels = _build_corpus(per_category=per_category, seed=seed)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["description", "category"])
        for text, label in zip(texts, labels):
            writer.writerow([text, label])
    return path, len(texts)


def _build_corpus(per_category=150, seed=42):
    texts, labels = [], []
    for category, samples in CURATED_SAMPLES.items():
        for s in samples:
            texts.append(s)
            labels.append(category)

    gen_texts, gen_labels = generate_synthetic_samples(per_category=per_category, seed=seed)
    texts.extend(gen_texts)
    labels.extend(gen_labels)
    return texts, labels


def _build_pipeline_objects():
    # Word-level TF-IDF captures topical vocabulary (e.g. "ransom", "injection").
    # Character-level TF-IDF (3-5 char windows) captures sub-word patterns so
    # the model isn't thrown off by an unseen inflection of a known word
    # (encrypt / encrypted / encryption all share character n-grams even
    # though they are three different tokens to a word-level vectorizer).
    # Combining both makes the model considerably more robust to incident
    # descriptions phrased differently than anything in the training set.
    vectorizer = FeatureUnion([
        ("word", TfidfVectorizer(max_features=700, ngram_range=(1, 2), min_df=2,
                                  stop_words="english", sublinear_tf=True)),
        ("char", TfidfVectorizer(max_features=500, ngram_range=(3, 5),
                                  analyzer="char_wb", sublinear_tf=True)),
    ])
    model = LogisticRegression(max_iter=4000, C=1.0, class_weight="balanced")
    return vectorizer, model


def train_text_model(save=True, verbose=True):
    from sklearn.metrics import accuracy_score

    texts, labels = _build_corpus()
    labels = np.array(labels)

    holdout_texts, holdout_labels = _build_holdout()
    holdout_labels = np.array(holdout_labels)

    realistic_texts, realistic_labels = _build_realistic_test()
    realistic_labels = np.array(realistic_labels)

    # --- Secondary diagnostic: stratified 5-fold cross-validation on the
    # training corpus itself. Useful to sanity check the pipeline, but on a
    # corpus that mixes hand-written and templated text this number tends to
    # run optimistic, because near-duplicate templated sentences can land in
    # both the train and validation fold of the same category. ---
    vectorizer_cv, model_cv = _build_pipeline_objects()
    X_cv = vectorizer_cv.fit_transform(texts)
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(model_cv, X_cv, labels, cv=skf)
    mean_cv_acc = float(np.mean(cv_scores))

    # --- Fit the FINAL deployed model on the full labeled training corpus ---
    vectorizer, model = _build_pipeline_objects()
    X_full = vectorizer.fit_transform(texts)
    model.fit(X_full, labels)

    # --- Realistic held-out accuracy: predictions on sentences written the
    # way a real user of the Analyzer page actually types (fairly direct,
    # often naming the attack or its standard symptoms). This is the number
    # surfaced to the app/UI, because it is the most relevant answer to
    # "how accurate is this in practice." ---
    X_realistic = vectorizer.transform(realistic_texts)
    realistic_preds = model.predict(X_realistic)
    realistic_acc = float(accuracy_score(realistic_labels, realistic_preds))

    # --- Hard held-out accuracy: a second, deliberately indirect/symptom-only
    # phrased set, used only as a documented stress test of the model's
    # limits - not surfaced as "the" accuracy, since it is harder than the
    # tool's actual expected usage. ---
    X_holdout = vectorizer.transform(holdout_texts)
    holdout_preds = model.predict(X_holdout)
    holdout_acc = float(accuracy_score(holdout_labels, holdout_preds))

    if verbose:
        print(f"[text_classifier] training corpus size: {len(texts)}")
        print(f"[text_classifier] 5-fold CV accuracy on training corpus: {mean_cv_acc:.4f} "
              f"(scores: {[round(s, 2) for s in cv_scores]})")
        print(f"[text_classifier] realistic held-out accuracy "
              f"({len(realistic_texts)} typical-phrasing examples): {realistic_acc:.4f}")
        print(f"[text_classifier] hard held-out accuracy "
              f"({len(holdout_texts)} indirect/symptom-only examples): {holdout_acc:.4f}")
        print(f"[text_classifier] categories: {sorted(set(labels.tolist()))}")

    if save:
        os.makedirs(config.AI_MODELS_DIR, exist_ok=True)
        joblib.dump(
            {"model": model, "vectorizer": vectorizer, "test_accuracy": realistic_acc,
             "cv_accuracy": mean_cv_acc, "hard_holdout_accuracy": holdout_acc,
             "categories": sorted(set(labels.tolist()))},
            MODEL_PATH,
        )
        csv_path, n_rows = export_dataset_csv()
        if verbose:
            print(f"[text_classifier] dataset exported: {csv_path} ({n_rows} rows)")
    return model, vectorizer, realistic_acc


_loaded = None


def _load_model():
    global _loaded
    if _loaded is None:
        if not os.path.exists(MODEL_PATH):
            train_text_model()
        _loaded = joblib.load(MODEL_PATH)
    return _loaded


def predict_text(description):
    bundle = _load_model()
    model = bundle["model"]
    vectorizer = bundle["vectorizer"]

    X = vectorizer.transform([description])
    proba = model.predict_proba(X)[0]
    classes = model.classes_

    ranked = sorted(zip(classes, proba), key=lambda t: t[1], reverse=True)
    top_category, top_prob = ranked[0]

    return {
        "input": description,
        "predicted_category": top_category,
        "confidence": round(float(top_prob) * 100, 2),
        "top_categories": [
            {"category": c, "probability": round(float(p) * 100, 2)} for c, p in ranked[:3]
        ],
        "model_test_accuracy": round(bundle.get("test_accuracy", 0) * 100, 2),
    }


if __name__ == "__main__":
    train_text_model()
